services:
  postgres-test:
    image: postgres:17-alpine
    container_name: postgres-test
    restart: on-failure:5 # política de reinício com limite de 5 tentativas
    env_file:
      - ./.env.e2e
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - test-network

  redis-test:
    image: redis:8-alpine
    container_name: redis-test
    restart: on-failure:5
    env_file:
      - ./.env.test
    networks:
      - test-network

  node-test:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    container_name: node-test
    env_file:
      - ./.env.test
    depends_on:
      - postgres-test
      - redis-test
    networks:
      - test-network
    volumes:
      - ./coverage:/app/coverage

networks:
  test-network:
    driver: bridge
