services:
  node-unit:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    container_name: node-unit
    environment:
      - NODE_ENV=test
      - JWT_SECRET=unittestsecret
      - JWT_EXPIRES_IN=1h
    volumes:
      - ./coverage:/app/coverage
      - ./server:/app
    command: ["npm", "run", "test:unit"]

networks:
  default:
    driver: bridge
