name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci --prefix server

      - name: Rodar ESLint
        run: npm run lint --prefix server

      - name: Verificar formatação (Prettier)
        run: npm run format:check --prefix server

  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci --prefix server

      - name: Compilar código
        run: npm run build --prefix server

  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes de integração
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from node-test

      - name: Upload coverage report (integration)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.test.yml down -v || true

  e2e-tests:
    name: Testes End-to-End
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes E2E
        run: |
          docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit --exit-code-from node-e2e-test

      - name: Upload coverage report (e2e)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-e2e
          path: coverage

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.e2e.yml down -v || true
